declare module 'vue' {
  export interface GlobalComponents {
    VarAppBar: typeof import('@varlet-vue2/ui')['_AppBarComponent']
    VarBackTop: typeof import('@varlet-vue2/ui')['_BackTopComponent']
    VarBadge: typeof import('@varlet-vue2/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet-vue2/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet-vue2/ui')['_CardComponent']
    VarCell: typeof import('@varlet-vue2/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet-vue2/ui')['_CheckboxComponent']
    VarCheckboxGroup: typeof import('@varlet-vue2/ui')['_CheckboxGroupComponent']
    VarChip: typeof import('@varlet-vue2/ui')['_ChipComponent']
    VarCol: typeof import('@varlet-vue2/ui')['_ColComponent']
    VarCountdown: typeof import('@varlet-vue2/ui')['_CountdownComponent']
    VarCounter: typeof import('@varlet-vue2/ui')['_CounterComponent']
    VarDivider: typeof import('@varlet-vue2/ui')['_DividerComponent']
    VarForm: typeof import('@varlet-vue2/ui')['_FormComponent']
    VarImage: typeof import('@varlet-vue2/ui')['_ImageComponent']
    VarIndexAnchor: typeof import('@varlet-vue2/ui')['_IndexAnchorComponent']
    VarIndexBar: typeof import('@varlet-vue2/ui')['_IndexBarComponent']
    VarInput: typeof import('@varlet-vue2/ui')['_InputComponent']
    VarLazy: typeof import('@varlet-vue2/ui')['_LazyComponent']
    VarLoading: typeof import('@varlet-vue2/ui')['_LoadingComponent']
    VarLocale: typeof import('@varlet-vue2/ui')['_LocaleComponent']
    VarMenu: typeof import('@varlet-vue2/ui')['_MenuComponent']
    VarOption: typeof import('@varlet-vue2/ui')['_OptionComponent']
    VarPagination: typeof import('@varlet-vue2/ui')['_PaginationComponent']
    VarProgress: typeof import('@varlet-vue2/ui')['_ProgressComponent']
    VarRadio: typeof import('@varlet-vue2/ui')['_RadioComponent']
    VarRadioGroup: typeof import('@varlet-vue2/ui')['_RadioGroupComponent']
    VarRate: typeof import('@varlet-vue2/ui')['_RateComponent']
    VarRipple: typeof import('@varlet-vue2/ui')['_RippleComponent']
    VarRow: typeof import('@varlet-vue2/ui')['_RowComponent']
    VarSelect: typeof import('@varlet-vue2/ui')['_SelectComponent']
    VarSkeleton: typeof import('@varlet-vue2/ui')['_SkeletonComponent']
    VarSnackbar: typeof import('@varlet-vue2/ui')['_SnackbarComponent']
    VarSpace: typeof import('@varlet-vue2/ui')['_SpaceComponent']
    VarStep: typeof import('@varlet-vue2/ui')['_StepComponent']
    VarSteps: typeof import('@varlet-vue2/ui')['_StepsComponent']
    VarSticky: typeof import('@varlet-vue2/ui')['_StickyComponent']
    VarSwipe: typeof import('@varlet-vue2/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet-vue2/ui')['_SwipeItemComponent']
    VarSwitch: typeof import('@varlet-vue2/ui')['_SwitchComponent']
    VarTab: typeof import('@varlet-vue2/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet-vue2/ui')['_TabItemComponent']
    VarTable: typeof import('@varlet-vue2/ui')['_TableComponent']
    VarTabs: typeof import('@varlet-vue2/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet-vue2/ui')['_TabsItemsComponent']
    VarTimePicker: typeof import('@varlet-vue2/ui')['_TimePickerComponent']
  }
}

export {}
